### ISSUE TITLE
PCB design

### ISSUE THREAD

**Issue by iqsam** [iquesters/nrg_single#1]
PCB design for Single port 9V 1amp, 9V 3amp and 12V 3amp

**Comment by iqsourav** [comment]
PCB design of 9V 1A, 12V 3A, 9V 3A uploaded on https://github.com/iquesters/nrg_single
All boards are in the same dimension 55mm x 65mm.

Regards,

**Comment by iqrohan** [comment]
@iqsourav In the 3 Amp designs, the mounting hole placements are not correct. There are components and traces within the t&b keepout layer. This needs to be changed.
Rest of the design is subject to prototype testing.
