### ISSUE TITLE
Circuit prototype

### ISSUE THREAD

**Issue by iqsam** [iquesters/nrg_single#3]
Etch, assemble and test working prototype for 9V 1amp, 9V 3amp and 12V 3amp

**Comment by iqsourav** [comment]
Etching, assembly of 9V,12V/3A is done. 9V,1A is pending along with the test report.

**Comment by iqsourav** [comment]
9V,12V/3A etching, assemble and testing working prototype done.

As hole positions are finalized new pcb design is made with few components placements changed, ie. Filter Choke, MOV, NTC, Fuse. New pcb will be etched and testing will be done.

**Comment by iqsourav** [comment]
Closing This issue as completed...
