### ISSUE TITLE
Component sourcing

### ISSUE THREAD

**Issue by iqsam** [iquesters/nrg_single#5]

**Comment by iqsourav** [comment]
Discussion needed related with components sourcing and selection of components.

**Comment by iqrohan** [comment]
Prototype for this milestone may have locally available components. Once prototype is finalised we will discuss and decide on actual components

**Comment by iqrohan** [comment]
@iqsam Rubber wire holder component sourcing is pending.

**Comment by iqsourav** [comment]
Quotation submitted to respective shops at chadni. need to follow up.

**Comment by iqsourav** [comment]
Transformer for 9v 3a and 12v 3a needed for sampling purpose.
