### ISSUE TITLE
NRG Single 1 Amp board layout

### ISSUE THREAD

**Issue by iqrohan** [iquesters/nrg_single#7]
1. All 1.5mm AC traces to be made 2mm trace as more space is available
2. Pri-Sec gap to be maintained atleast 6.5 mm. Check Y-Cap area.
3. Secondary side rectifier diode's PCB heat-sink to be increased and made atleast similar to NRG if not more.
_NRG (approx): anode-127.5 sq.mm, cathode-126.5sq.mm_
_This design (approx): anode-73.5 sq.mm, cathode-103.5 sq.mm_
4. TNY-SW PCB heat-sink to be made atleast 30 sq.mm more as more space is available
5. The cable clamp's rotation limit is not done here. Can be done using burg or relimate placement.

**Comment by iqsourav** [comment]
Following Points done... Testing work in progress.
